### PR TITLE
Adding nodejs 'getting-started' devfile

### PR DESCRIPTION
**Pull request by ibuziuk**
https://github.com/redhat-developer/rh-che/issues/1451

### CODE REVIEW

**Comment by Katka92** [comment]
The devfile is started correctly, all commands (except debug - didn't know how to debug) works as expected. Suggestions are shown, code navigation works, preview is displayed and works correctly, autocomplete works. Changes in a code are reflected correctly and are shown in preview after refreshing a page.
What is quite irritating is that every time I do some "breaking change" (e.g. I'm writing too slowly, I want to read the suggestions for a command etc.) the build of a application fails. That means that once I fix the change (e.g. I write the rest of a command) the application is build and the pop-up is displayed on foreground. I can click "Open link" or "cancel" and then refresh a page to see the new result. So, if it is possible, I would disable autosave for a quick start or increase a time for that.
nodejs

**Comment by ibuziuk** [comment]
@Katka92 well, you can disable auto-save on IDE level:
image

I do not think there is an option to disable auto-save on devfile level

**Comment by ibuziuk** [comment]
for debugging you need to run the app in the debug mode and execute "Debug" -> "Start Debugging" in IDE

**Review by amisevsk — APPROVED** [review]
LGTM

**Comment by amisevsk** [comment]
I've opened issue https://github.com/eclipse/che/issues/14160 for the constant listening notification; it's been bothering me too.

**Pull request merged**
