### PR TITLE
Adding spring-petclinic 'getting-started' devfile

### PR DESCRIPTION
**Pull request by ibuziuk**
https://github.com/redhat-developer/rh-che/issues/1451

### CODE REVIEW

**Review by Katka92 — APPROVED** [review]
The devfile is started correctly, all commands works as expected. Suggestions are shown, code navigation works, preview is displayed and works correctly, autocomplete works. Changes in a code are reflected correctly after build&run. 
The only weird thing I found is that when I run `che: stop webapp` the error is shown [1]. It is probably workaround for the issue that `Terminate task` command does not work https://github.com/eclipse/che/issues/13737.

**Comment by ibuziuk** [comment]
@Katka92 but the app was stopped successfully, right ?

**Comment by Katka92** [comment]
@ibuziuk Yeah, the app was killed successfully - but that raise the error. It is working but confusing. But as far as it is (I think) workaround for the `Terminate task` I'm ok with that.

**Review by amisevsk — APPROVED** [review]
Tested and everything works, LGTM.

Regarding the error when running the "stop webapp" task, that is expected since it sends `SIGTERM` to the server and causes it to exit with status 143: I see the notifications

```
Task 3 has exited with code 0 (this is the stop task)
Task 2 has exited with code 143. (this is the run task)
```

Debugging works as expected.

**Pull request merged**
